version: '3'
services:
  redis:
    image: redis:6
    networks:
      - ne-student-network
    container_name: studa-redis
    volumes:
        - ./redis-data:/var/lib/redis
        - ./redis.conf:/usr/local/etc/redis/redis.conf
    command:
      redis-server --requirepass ${REDIS_PASSWORD}

  postgres:
    image: postgres:12-alpine
    networks:
      - ne-student-network
    container_name: studa-postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSRGRES_DB: nestudent
  
  api:
    image: docker.pkg.github.com/ne-student/api/api
    # build: .
    container_name: api
    networks:
      - ne-student-network
    environment:
      PORT: 5505
      HOST: 0.0.0.0
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@studa-postgres/nestudent
      RUST_LOG: actix,ne-student-api
      TOKEN_SECRET: ${TOKEN_SECRET}
      REDIS_URL: redis://:${REDIS_PASSWORD}@studa-redis
    ports:
      - ${PORT}:5505
    depends_on: 
      - postgres

networks:
  ne-student-network: